application = rediff
platform = prod
url = https://portfolio.rediff.com/portfolio-login


#login
useremail_id=useremail
password_css=#userpass
login_submit_id=loginsubmit
remember_checkbox_xpath=//input[@name='remember']


#create Portfolio
create_xpath=//a[@id='createPortfolio']
name_xpath=//div[@class='formField']/following::input[@name='create']
createPortfolio_xpath=//div[@class='btnRhtGrySml']//input[@id='createPortfolioButton']


#dropDown List 
dropdown_xpath = //select[@id='portfolioid']


#Delete portfolio
delete_id =deletePortfolio

#Add Stock
addstock_xpath=//input[@id='addStock']
addstockname_id=addstockname

stockPurchaseDate_id =stockPurchaseDate
monthyear_css=div.dpTitleText
datebackButton_xpath=//*[@id='datepicker']/table/tbody/tr[1]/td[2]/button

addstockqty_id=addstockqty
addstockprice_id=addstockprice
addStockButton_id=addStockButton


stocktable_css=table#stock > tbody
equityaction_id=equityaction
buySellCalendar_id=buySellCalendar
buysellqty_id=buysellqty
buysellprice_id=buysellprice
buySellStockButton_id=buySellStockButton
latestShareChangeQuantity_xpath=//table[@class='dataTable']/tbody/tr[1]/td[3]